from flask import Flask, render_template, flash
import os
import json

app = Flask(__name__)
app.secret_key = os.urandom(24)

RESULTS_FILE = "aggregated_results.json"  # The file generated by integrated_scanner.py

@app.route('/')
def index():
    results = []
    try:
        with open(RESULTS_FILE, 'r') as f:
            results = json.load(f)
    except Exception:
        flash("No scan results available yet. Please run the scanner first.")
    return render_template('index.html', results=results)

if __name__ == '__main__':
    app.run(debug=True, host='0.0.0.0')
